const data = [
  {
    name: "위드",
    description: "EdTech 스타트업입니다.",
    category: "에듀테크",
    simInvest: 100,
    actualInvest: 120,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "에스프레소",
    description: "교육 관련 서비스 제공합니다.",
    category: "에듀테크",
    simInvest: 80,
    actualInvest: 100,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "코드잇",
    description: "프로그래밍 교육 스타트업.",
    category: "에듀테크",
    simInvest: 70,
    actualInvest: 90,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "엘리스",
    description: "온라인 교육 플랫폼 제공.",
    category: "에듀테크",
    simInvest: 60,
    actualInvest: 80,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "알고랩",
    description: "AI 교육 전문 스타트업.",
    category: "에듀테크",
    simInvest: 50,
    actualInvest: 70,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "브레인",
    description: "AI 기반 학습 솔루션.",
    category: "에듀테크",
    simInvest: 90,
    actualInvest: 110,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "지니어스",
    description: "교육 분석 서비스 제공.",
    category: "에듀테크",
    simInvest: 85,
    actualInvest: 105,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "마스터클래스",
    description: "전문가와 함께하는 강의 플랫폼.",
    category: "에듀테크",
    simInvest: 75,
    actualInvest: 95,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "에듀팜",
    description: "커리큘럼 설계 서비스.",
    category: "에듀테크",
    simInvest: 65,
    actualInvest: 85,
    logo: "img/companyLogo/codeit.png",
  },
  {
    name: "리딩업",
    description: "리딩 교육 특화 서비스.",
    category: "에듀테크",
    simInvest: 55,
    actualInvest: 75,
    logo: "img/companyLogo/codeit.png",
  },
];

export default data;